language: node_js
  node_js:
  - node
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

before_script:
  - npm install -g ganache-cli --supress-warnings
  - npm install -g truffle@5.1.44 --supress-warnings

install:
  - npm install --supress-warnings

script:
  - ganache-cli &
  - sleep 5
  - truffle test
  - truffle migrate
