language: node_js
  - "12"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - npm install -g ganache-cli
  - npm install -g truffle@5.1.44

install:
  - npm install --supress-warnings

script:
  - ganache-cli &
  - sleep 5
  - truffle test
  - truffle migrate
